### ISSUE TITLE
License for Presets/Instruments?

### ISSUE THREAD

**Issue by afarlie** [zynaddsubfx/instruments#2]
There is no licensing information provided for the banks provided.

**Comment by fundamental** [comment]
Licenses for instrument patches are typically supplied per instrument file. Additionally the output audio of the synth is independent of the license of any data files.

**Comment by afarlie** [comment]
Thanks.  I  had assumed that the  data is embedded in the instrument files themselves,  because I was not seeing any separate license file information such as a (COPYING or LICENSE.txt) in the repository.

However, in examining some sample Patches/Instrument definitions, I am not finding an 'explicit' licensing entry ( Such as CC-0 or CC-BY-3.0), or even .  This means that despite as you explain the audio output not being under the same license,  I feel I can't put them into "production" use.   As the intent of having an instrument repository would seem to be to have useful and interesting instruments shared for use by the community of users,  explicit clarity about what can and can't be done with supplied patches would be very much appreciated.

I'm sorry if I sound overly cautious, but past experience has suggested that unless something is explicitly licensed as "free" (Creative Commons sense), It's generally not safe to assume any other license. 

My recommendation would be to insist on a clear licensing statement (in the instrument metadata- i.e Author/copyright field) for third-party submitted instruments, and an audit of the existing ones, adding the appropriate information.  ( I'm very strongly in favour of  Creative Commons style licensing for shared repositorys of Presets/Patches.)

Should I raise a new issue suggesting this , or would there be a more appropriate forum to raise these concerns on?

**Comment by afarlie** [comment]
I will also note on examining the Author/Copyright field (accessed from the "Edit Instrument" button.) I was not always finding explicit licensing information, ( If it was the intent that these were at the very least CC-BY, that should be in the meta-data in my view).

**Comment by fundamental** [comment]
If you want to personally go through the process of updating individual patch metadata, then that should be fine, however this is not a task that I have the time or desire to work on myself.

**Comment by afarlie** [comment]
I'm sorry, but I can't actually update the instrument data's Licensing meta-data as I'm not the copyright holder or creator.  I thus have no way of knowing other than an explicit indication what license they (the original creators) had actually intended, where this information isn't present in the repository.

Without an explicitly specified indication, there's no way to know which file is CC-0, which is CC-BY etc..  Whilst I can accept there is an "implied" (personal use) license , this isn't a useful license, given proposed changes to copyright policy in Europe.

**Comment by tresf** [comment]
> typically supplied per instrument file

Two questions:
1. What if they're not supplied?  What license should users apply?
2. If they are supplied, where do we find this information?  I would be happy with UI instructions or a command-line parsing approach.  (I'm on the old interface still)

In my case, I have a user that wants to share some Zyn presets, but does not know if they can since they are based off of another work.  (in this case DX Rhodes).  I'm struggling to locate what the implied license is if this information cannot be found.  I understand the project is GPL, but this license is not very clear (as opposed to most of the CC- licenses which clearly state what artists can do with them).

I understand the sounds are not subject to the same restrictions, but in my case, the user wants to share these derivative works (as presets) with others and if they choose an incompatible license from the original, this would be unethical (and possibly illegal), so I want to be able to answer the user's question with certainty.

Here's an example of a derivative work: https://lmms.io/lsp/?action=show&file=22489.  Notice that the user is forced on the sharing platform to select a license, but the user is unsure as to what they CAN chose do the ambiguity of the license as described by the OP.  Any clarity is greatly appreciated. ❤️

**Comment by fundamental** [comment]
Unfortunately I don't have much information to add to this issue, I will say that patches were either directly contributed by authors to one of the zyn repos, via the kvr file shares, or via the zynaddsubfx-user mailing list.

**Comment by fundamental** [comment]
As per the UI view, the information is still there, though it may not be exposed in the zyn-fusion UI. Resolving that would likely be an enhancement, but as you can see users were never entirely consistent with listing the information others may want.

**Comment by tresf** [comment]
> Unfortunately I don't have much information to add to this issue, I will say that patches were either directly contributed by authors to one of the zyn repos, via the kvr file shares, or via the zynaddsubfx-user mailing list.

Me neither.  The GPL makes it hard to understand how the original presets are allowed to distributed outside of a codebase.  Searching this problem on S.O shows a lot of people with a similar question (usually asking about artwork), but no concrete answer.
